#!/bin/bash
pip install pywebview[qt]
echo 'An administrator password is required to continue installation.';
cd /
sudo wget "https://raw.githubusercontent.com/JustAnEric/hostereric/main/lightweightspotto.py?token=GHSAT0AAAAAACDHPWFTMX4KLXUGBSZDV77AZDURZ6A"
clear;
cd /usr/bin
sudo printf "echo 'Command line tool for Lightweight Spotify isn\'t supported yet. Please see the official guide.'" > lwspotify;
sudo chmod -rw lwspotify;
sudo chmod +x lwspotify;
cd /
echo "Installation complete. Lightweight Spotify is installed."
cd ~
