#!/bin/bash
pip install pywebview[qt]
echo 'An administrator password is required to continue installation.';
sudo su;
wget "https://raw.githubusercontent.com/JustAnEric/hostereric/main/lightweightspotto.py?token=GHSAT0AAAAAACDHPWFTMX4KLXUGBSZDV77AZDURZ6A"
clear;
echo "Installation complete. Lightweight Spotify is installed."
